# Generated by Django 4.1.7 on 2023-02-17 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_relationship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
